#!/bin/bash
#
# arvude summa leidmine
#
# genereerime arvud
summa=0
for ((arv=1; arv<11; arv++))
do
	# leiame kõikide arvude hulgas paarisarvud
	# selleks jagame arvu 2-ga ja arvutame jäägi
	jaak=$(($arv % 2))
	# juhul, kui jääk on 0, on tegu paarisarvuga
if [ $jaak -eq 0 ]; then
	# arvutame summa välja
	summa=$(($summa + $arv))
fi # if lause lõppu

done
echo "arvude 1..10 paarisarvude summa on $summa"


