#!/bin/bash
#
# Skript kontrollib faili olemasolu ja kustutab selle ning väljastab teate
# Kristjan Roogsoo IS116
if [ $# -ne 1 ]; then
echo "Kasutus $0 faili nimi"
else
 file="$1"
 if [ -f $file ]; then
	rm $file
	echo "Fail $1 on kustutatud"
	
 else
	echo "Faili $file pole"
 fi
fi
